[project]
name = "fractals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.3.0",
    "matplotlib>=3.9.2",
    "pillow>=10.4.0",
    "pyfracgen>=0.3.0",
]
